on:
  schedule:
    - cron: '0 0 5 * *'
  push:
    branches:
      - 'master'

name: "Build And Push PHP Docker Images"

jobs:
  build-and-push-docker:
    name: "Build And Push PHP Docker Images"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Generate Docker files"
        working-directory: arch-linux
        run: make

      - name: "Build base images"
        working-directory: arch-linux
        run: make docker-build-base

      - name: "Push base images"
        working-directory: arch-linux
        run: make docker-push-base

      - name: "Build images"
        working-directory: arch-linux
        run: make docker-build

      - name: "Push images"
        working-directory: arch-linux
        run: make docker-push


